services:
  flask:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - 5001:5001
    image: api:v1
    container_name: api
  
  brocker:
    build:
      context: ./brocker
      dockerfile: Dockerfile
    ports: 
      - 1883:1883
    image: brocker:v1
    container_name: broker
  
  database:
    build:
      context: ./database
      dockerfile: Dockerfile
    ports:
      - 5432:5432
    image: database:v1
    container_name: postgres
