# Zapisuj stan brokera (np. wiadomości typu "retained")
persistence true
persistence_location /mosquitto/data/

# Włącz logowanie do konsoli, żeby Docker je widział
log_dest stdout

# Zezwól na łączenie się anonimowych użytkowników
allow_anonymous true

# Ustaw nasłuchiwanie na domyślnym porcie
listener 1883
